Allow longer filenames in crate assembler (#28)
## What is the goal of this PR?

The `deploy-crate-snapshot` task in CI fails because a newly introduced
module pushed the path length to being just over 100 bytes, triggering
the following error:
```
Action assemble_crate.crate failed: (Exit 1): crate-assembler failed: error executing command bazel-out/host/bin/external/vaticle_bazel_distribution/crates/crate-assembler --srcs ... (remaining 29 arguments skipped)

java.lang.IllegalArgumentException: file name 'typedb-client-0.0.0-d56ec4d4e590db3db79ef42118e1cb9aee86329d/src/connection/cluster/database_manager.rs' is too long ( > 100 bytes)
```

This issue was fixed by switching to the POSIX tar headers in
bazel-distribution. This PR propagates this change via dependencies into
client-rust.

## What are the changes implemented in this PR?

We update the vaticle dependencies to point at the version with the
updated `assemble_crate` rule.